{% set name = "conda-suggest" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda-incubator/conda-suggest/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 377bdb8362356c325bc3017b4f90327913d0a8eb4f160a0e66514f4550c4b075

build:
  noarch: python
  number: 1
  script:
    - "{{ PYTHON }} -m pip install . -vv"
    - mkdir -p {{ PREFIX }}/etc/conda/activate.d
    - mkdir -p {{ PREFIX }}/etc/conda/deactivate.d
    - cp {{ RECIPE_DIR }}/activate.sh {{ PREFIX }}/etc/conda/activate.d/activate-conda-suggest.sh
    - cp {{ RECIPE_DIR }}/deactivate.sh {{ PREFIX }}/etc/conda/deactivate.d/deactivate-conda-suggest.sh
  entry_points:
    - conda-suggest = conda_suggest.main:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - tqdm
    - conda-suggest-conda-forge

test:
  imports:
    - conda_suggest
  commands:
    - conda-suggest --help

about:
  home: https://github.com/conda-incubator/conda-suggest
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Suggests packages to install to obtain command line utilities'
  dev_url: https://github.com/conda-incubator/conda-suggest

extra:
  recipe-maintainers:
    - scopatz
    - isuruf
